### ISSUE TITLE
C header files matching your running kernel were not found

### ISSUE THREAD

**Issue by backtoback1** [pavlinux/vmware-modules#1]
HI i have problem with vmware workstation v 14 (latest version) 
with kernel 4.14 (kali linux )
but the VM don't want to run it's show me this error : 
C header files matching your running kernel were not found
i install the kernel header 4.14 and linux-image 4.14
and also change vm files as your 
but it's still not working the same problem

**Comment by pavlinux** [comment]
# export SYSSRC=/usr/src/linux-headers-a.b.c-foo-bar/  
# make;

**Comment by pavlinux** [comment]
```
man man; 
man make;
 
```

**Comment by pavlinux** [comment]
ls -la /lib/modules/`uname -r`/build/  ?

**Comment by backtoback1** [comment]
solved 
Thanks

**Comment by nareshbc5555** [comment]
hello there
 how did you solved it ?? exactly.
i'm new beginner so . please elaborate it.
